# Maven
# Build, test, and deploy with Apache Maven
trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  name: Agent
  inputs:
    secureFile: 'application-secrets.yml'
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml' 
    goals: 'package' # Optional
    options: -Dspring.config.location=classpath:/,$(Agent.secureFilePath) # Optional
    publishJUnitResults: true 
    testResultsFiles: '**/surefire-reports/TEST-*.xml' # Required when publishJUnitResults == True
    testRunTitle: # Optional
    codeCoverageToolOption: 'None' # Optional. Options: none, cobertura, jaCoCo. Enabling code coverage inserts the `clean` goal into the Maven goals list when Maven runs.
    codeCoverageClassFilter: # Optional. Comma-separated list of filters to include or exclude classes from collecting code coverage. For example: +:com.*,+:org.*,-:my.app*.*
    codeCoverageClassFilesDirectories: # Optional
    codeCoverageSourceDirectories: # Optional
    codeCoverageFailIfEmpty: false # Optional
    javaHomeOption: 'JDKVersion' # Options: jDKVersion, path
    jdkVersionOption: '1.11' # Optional. Options: default, 1.11, 1.10, 1.9, 1.8, 1.7, 1.6
    jdkDirectory: # Required when javaHomeOption == Path
    jdkArchitectureOption: 'x64' # Optional. Options: x86, x64
    mavenVersionOption: 'Default' # Options: default, path
    mavenDirectory: # Required when mavenVersionOption == Path
    mavenSetM2Home: false # Required when mavenVersionOption == Path
    mavenOptions: '-Xmx1024m' # Optional
    mavenAuthenticateFeed: false 
    effectivePomSkip: false 
    sonarQubeRunAnalysis: false 
    sqMavenPluginVersionChoice: 'latest' # Required when sonarQubeRunAnalysis == True# Options: latest, pom
    checkStyleRunAnalysis: false # Optional
    pmdRunAnalysis: false # Optional
    findBugsRunAnalysis: false # Optional
- task: PublishCucumberReport@1
  displayName: 'Publish Cucumber Report'
  condition: succeededOrFailed()
  inputs:
    jsonDir: ./results
    outputPath: ./results
    name: 'Automated Tests'
    title: Cucumber tests
    theme: 'bootstrap'